# Generated by Django 6.0.5 on 2026-05-25 12:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Establishment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('primaire', 'Primaire'), ('secondaire', 'Secondaire'), ('lycee', 'Lycee'), ('universite', 'Universite'), ('autre', 'Autre')], max_length=30)),
                ('adresse', models.TextField()),
                ('ville', models.CharField(max_length=100)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('pays', models.CharField(default='Cameroun', max_length=100)),
                ('telephone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('site_web', models.URLField(blank=True)),
                ('niveaux_scolaires', models.JSONField(blank=True, default=list)),
                ('capacite', models.PositiveIntegerField(blank=True, null=True)),
                ('annee_creation', models.PositiveIntegerField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('en_attente', 'En attente'), ('publie', 'Publie'), ('rejete', 'Rejete'), ('archive', 'Archive')], default='en_attente', max_length=30)),
                ('motif_rejet', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('directeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='etablissements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nom'],
                'indexes': [models.Index(fields=['statut'], name='establishme_statut_7577ad_idx'), models.Index(fields=['ville'], name='establishme_ville_7eb628_idx'), models.Index(fields=['type'], name='establishme_type_e775fb_idx')],
            },
        ),
    ]
