# Generated by Django 6.0.5 on 2026-05-25 13:51

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('establishments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('note', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('approuve', 'Approuve'), ('rejete', 'Rejete')], default='en_attente', max_length=20)),
                ('motif_rejet', models.TextField(blank=True)),
                ('date_publication', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commentaires', to=settings.AUTH_USER_MODEL)),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='establishments.establishment')),
            ],
            options={
                'ordering': ['-date_publication'],
                'indexes': [models.Index(fields=['statut'], name='comments_co_statut_68b2e6_idx'), models.Index(fields=['etablissement', 'statut'], name='comments_co_etablis_2d1d59_idx')],
                'constraints': [models.UniqueConstraint(fields=('auteur', 'etablissement'), name='unique_comment_per_user_establishment')],
            },
        ),
    ]
